import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex `}
      >
        <ul className="max-h-100vh p-4 flex flex-col gap-4 border-r border-gray-300">
          <li>
            <Link href={"/"}>Home</Link>
          </li>
          <li>
            <Link href={"/debounce"}>#1 Debounce Example - Nov 13 2025</Link>
          </li>
          <li>
            <Link href={"/flattenobj"}>#2 Flatten Object - Nov 13 2025</Link>
          </li>
        </ul>
        <span className="p-4">{children}</span>
      </body>
    </html>
  );
}
